package org.jotserver.ot.model.item;

public enum ItemAttribute { 
	ALWAYSONTOP, 
	FLOORCHANGEDOWN, 
	FLOORCHANGEWEST, 
	FLOORCHANGESOUTH, 
	FLOORCHANGEEAST, 
	FLOORCHANGENORTH, 
	BLOCKSOLID, 
	BLOCKPROJECTILE, 
	BLOCKPATHFIND, 
	PICKUPABLE, 
	STACKABLE, 
	MOVEABLE,
	HASHEIGHT, 
	USEABLE,
	VERTICAL,
	HORIZONTAL,
	DISTREAD,
	ROTABLE,
	READABLE,
	CORPSE,
	HANGABLE;
}
